"use client";

import Link from "next/link";

import { useLanguage } from "@/components/language-provider";
import { siteConfig } from "@/site-config";

const privacyCopy = {
  zh: {
    eyebrow: "隐私政策",
    title: "南湾咨询隐私政策",
    summary: `本隐私政策说明${siteConfig.legalNameCn}（英文名：${siteConfig.legalNameEn}）如何通过本网站及相关业务沟通渠道收集、使用、保存和保护信息。`,
    companyLabel: "公司名称",
    addressLabel: "注册地址",
    dateLabel: "生效日期",
    backButton: "返回联系信息",
    sections: [
      {
        title: "信息收集",
        paragraphs: [
          "南湾咨询可能会收集访问者通过网站咨询、正式联系渠道或后续服务沟通中主动提供的信息，包括姓名、公司名称、电子邮箱、电话号码、留言内容以及访问者自愿提交的其他资料。",
          "在访问网站过程中，我们也可能接收由服务器、托管平台或分析基础设施自动生成的有限技术信息，例如浏览器类型、设备信息、访问页面、访问时间以及常规日志数据。",
        ],
      },
      {
        title: "信息使用",
        paragraphs: [
          "南湾咨询收集的信息主要用于网站运行、回复咨询、评估服务需求、优化沟通体验、开展内部管理以及在法律法规要求下履行必要义务。",
          "通过网站提交的咨询信息，可能会被转发至公司的业务邮箱或其他经授权的内部跟进系统，以便及时处理相关需求。",
        ],
        items: [
          "用于回复访问者问题并提供所请求的咨询信息。",
          "用于留存与合法业务咨询相关的基础记录。",
          "用于提升网站展示效果、稳定性与访问体验。",
          "用于满足适用法律、合法请求或争议处理需要。",
        ],
      },
      {
        title: "信息安全",
        paragraphs: [
          "南湾咨询采取合理的管理、技术和组织措施，以防止信息遭到未经授权的访问、误用、篡改、泄露或丢失。尽管任何网站或传输方式都无法保证绝对安全，我们仍会根据所处理信息的性质采取相称的保护措施。",
          "仅在具有正当业务需要的情况下，相关员工、代表或服务提供方才可接触所提交的信息，并应当以审慎、负责的方式进行处理。",
        ],
      },
      {
        title: "共享与披露",
        paragraphs: [
          "南湾咨询不会通过本网站出售个人信息。若为网站运行、业务支持、权利保护、安全保障或遵守法律所必需，我们可能与可信赖的服务提供方、专业顾问或有权机关共享相关信息。",
        ],
      },
      {
        title: "留存与联系",
        paragraphs: [
          "相关信息将在实现收集目的、保留必要业务记录、处理争议、执行约定或履行法律义务所需的合理期间内保存。",
          `如需就本网站隐私事项进行沟通，可向${siteConfig.legalNameCn}注册地址${siteConfig.address}提交书面联系。`,
        ],
      },
    ],
  },
  en: {
    eyebrow: "Privacy Policy",
    title: "Privacy Policy for Nanwan Consulting",
    summary: `This Privacy Policy explains how ${siteConfig.legalNameCn}, also referred to as ${siteConfig.legalNameEn}, may collect, use, store, and protect information obtained through this website and related business communications.`,
    companyLabel: "Company",
    addressLabel: "Registered Address",
    dateLabel: "Effective Date",
    backButton: "Return to Contact Section",
    sections: [
      {
        title: "Data Collection",
        paragraphs: [
          "Nanwan Consulting may collect information that visitors voluntarily provide through website enquiries, approved contact channels, or future consultation requests. This may include a name, company name, email address, phone number, message content, and any additional details a visitor chooses to submit.",
          "We may also receive limited technical information automatically when this website is accessed, such as browser type, device information, pages visited, general region, access times, and standard log data generated by hosting or analytics infrastructure.",
        ],
      },
      {
        title: "Use of Information",
        paragraphs: [
          "Information collected by Nanwan Consulting is used to operate the website, respond to business enquiries, evaluate service requests, improve communication, support internal administration, and meet legal or regulatory obligations when required.",
          "Website enquiry submissions may be routed to the company's business mailbox or other authorized internal follow-up systems so that requests can be handled promptly.",
        ],
        items: [
          "To respond to questions and provide requested consulting information.",
          "To maintain business records connected to legitimate enquiries.",
          "To improve website presentation, reliability, and visitor experience.",
          "To comply with applicable law, lawful requests, or dispute resolution needs.",
        ],
      },
      {
        title: "Security",
        paragraphs: [
          "Nanwan Consulting uses reasonable administrative, technical, and organizational measures to protect information against unauthorized access, misuse, alteration, disclosure, or loss. While no website or transmission method can be guaranteed to be completely secure, we work to apply proportionate safeguards suitable for the nature of the information involved.",
          "Access to submitted information is limited to personnel, representatives, or service providers who require it for legitimate business purposes and who are expected to handle it responsibly.",
        ],
      },
      {
        title: "Sharing and Disclosure",
        paragraphs: [
          "Nanwan Consulting does not sell personal information through this website. We may share information with trusted service providers, professional advisors, or competent authorities when such sharing is necessary to operate the website, support business activities, protect rights or safety, or comply with law.",
        ],
      },
      {
        title: "Retention and Access",
        paragraphs: [
          "Information is retained for as long as reasonably necessary to fulfill the purpose for which it was collected, maintain business records, resolve disputes, enforce agreements, or comply with legal obligations.",
          `Privacy-related enquiries concerning this website may be directed in writing to the registered address of ${siteConfig.legalNameCn} at ${siteConfig.address}.`,
        ],
      },
    ],
  },
} as const;

export function PrivacyPageContent() {
  const { language } = useLanguage();
  const copy = privacyCopy[language];

  return (
    <div className="policy-shell">
      <section className="policy-hero reveal">
        <p className="eyebrow">{copy.eyebrow}</p>
        <h1 className="policy-title">{copy.title}</h1>
        <p className="policy-summary">{copy.summary}</p>

        <div className="meta-grid">
          <div className="meta-item">
            <span>{copy.companyLabel}</span>
            <strong>{siteConfig.legalNameCn}</strong>
          </div>
          <div className="meta-item">
            <span>{copy.addressLabel}</span>
            <strong>{siteConfig.address}</strong>
          </div>
          <div className="meta-item">
            <span>{copy.dateLabel}</span>
            <strong>
              {language === "zh"
                ? siteConfig.privacyEffectiveDateCn
                : siteConfig.privacyEffectiveDateEn}
            </strong>
          </div>
        </div>

        <div className="button-row">
          <Link className="secondary-button" href="/#contact">
            {copy.backButton}
          </Link>
        </div>
      </section>

      {copy.sections.map((section, index) => (
        <section
          key={section.title}
          className={`policy-section reveal ${index > 1 ? "delay-2" : "delay-1"}`}
        >
          <h2>{section.title}</h2>
          {section.paragraphs.map((paragraph) => (
            <p key={paragraph}>{paragraph}</p>
          ))}
          {"items" in section && section.items ? (
            <ul className="policy-list">
              {section.items.map((item: string) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          ) : null}
        </section>
      ))}
    </div>
  );
}
